{
 "title": "OTUS HW5 Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, avg by(le) (increase(http_server_duration_bucket{net_host_port=\"8000\"}[1m])))",
     "legendFormat": "q=0,5"
    },
    {
     "expr": "histogram_quantile(0.95, avg by(le) (increase(http_server_duration_bucket{net_host_port=\"8000\"}[1m])))",
     "legendFormat": "q=0,95"
    },
    {
     "expr": "histogram_quantile(0.99, avg by(le) (increase(http_server_duration_bucket{net_host_port=\"8000\"}[1m])))",
     "legendFormat": "q=0,99"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum (rate(http_server_duration_bucket{net_host_port=\"8000\"}[1m])/60)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS by METHOD",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum by(http_method) (rate(http_server_duration_bucket{net_host_port=\"8000\"}[1m])/60)",
     "legendFormat": "{{200}}"
    }
   ]
  },
  {
   "title": "Latency by Method (q=0,99)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, http_method) (increase(http_server_duration_bucket{net_host_port=\"8000\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Процент 500 ответов",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum (rate(http_server_duration_bucket{net_host_port=\"8000\", http_status_code=\"500\"}[1m]))/ sum (rate(http_server_duration_bucket{net_host_port=\"8000\"}[1m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB response latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(db_client_operation_duration_bucket[1m])))",
     "legendFormat": "q=0,5"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(db_client_operation_duration_bucket[1m])))",
     "legendFormat": "q=0,95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(db_client_operation_duration_bucket[1m])))",
     "legendFormat": "q=0,99"
    }
   ]
  },
  {
   "title": "Users count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "targets": [
    { "expr": "my_users_count", "legendFormat": "__auto" }
   ]
  }
 ]
}