{
 "title": "MyMetrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Infrastructure Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Error Response Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(my_http_requests_total{route!~\"(.*)health(.*)\", route!=\"/metrics\", status_code=~\"4(.*)\"}[1m])) / sum (rate(my_http_requests_total{route!~\"(.*)health(.*)\", route!=\"/metrics\"}[1m])) * 100",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(my_http_requests_total{route!~\"(.*)health(.*)\", route!=\"/metrics\", status_code=~\"5(.*)\"}[1m])) / sum (rate(my_http_requests_total{route!~\"(.*)health(.*)\", route!=\"/metrics\"}[1m])) * 100",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(my_http_request_duration_seconds_bucket{route!~\"(.*)health(.*)\", route!=\"/metrics\"}[1m])))",
     "legendFormat": "le=0.95"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(my_http_request_duration_seconds_bucket{route!~\"(.*)health(.*)\", route!=\"/metrics\"}[1m])))",
     "legendFormat": "le=0.9"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(my_http_request_duration_seconds_bucket{route!~\"(.*)health(.*)\", route!=\"/metrics\"}[1m])))",
     "legendFormat": "le=0.99"
    }
   ]
  },
  {
   "title": "RPS for Services",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "avg by(instance) (rate(my_http_requests_total{route!~\"(.*)health(.*)\", route!=\"/metrics\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency by Service (LE=0.95)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, avg by(le, instance) (rate(my_http_request_duration_seconds_bucket{route!~\"(.*)health(.*)\", route!=\"/metrics\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Business Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "User Registration",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
   "targets": [
    { "expr": "sum by(type) (my_users_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Processed Orders per minute by status",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "rate(my_orders_executed_total[1m])",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}