apiVersion: v1
kind: Service
metadata:
  name: erp-svc
  namespace: otus-anton
spec:
  selector:
    app: erp-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: erp-port
      name: web-erp-port
  type: NodePort