apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-app
  namespace: otus-anton
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: profile-app
  template:
    metadata:
      labels:
        app: profile-app
    spec:
      automountServiceAccountToken: false
      initContainers:
        - name: wait-for-kafka
          image: busybox:1.28
          command:
            - "sh"
            - "-c"
            - "until nc -z franz-kafka 9092; do echo 'Waiting for Kafka...'; sleep 5; done"
        - name: wait-for-postgres
          image: busybox:1.28
          command:
            - "sh"
            - "-c"
            - "until nc -z postgres-postgresql 5432; do echo 'Waiting for PostgreSQL...'; sleep 5; done"
      containers:
        - name: profile-app
          image: antonkurudinov/otus_hw10_profile:1.0
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8000
              name: profile-port
          livenessProbe:
            httpGet:
              port: 8000
              path: /profile/health
            initialDelaySeconds: 10
            periodSeconds: 30
          envFrom:
            - configMapRef:
                name: db-settings
            - secretRef:
                name: db-secret

